name = "Microeconometrics"
uuid = "5d8a72c5-1e5a-5861-b6ae-c8e9564f9d17"
version = "0.4.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[compat]
CSV = "≥ 0.3.0"
DataFrames = "≥ 0.13.0"
Format = "≥ 0.7.0"
Optim = "≥ 0.17.0"
SpecialFunctions = "≥ 0.7.0"
StatsBase = "≥ 0.25.0"
StatsFuns = "≥ 0.7.0"
StatsModels = "0.3, 0.4, 0.5"
julia = "≥ 1.0.0"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "StatsModels", "StatsBase", "Test", "DataFrames"]
